version: 2

models:
  - name: fact_orders
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - order_item_id
      - dbt_utils.expression_is_true:
          arguments:
            expression: "total_amount = price + freight_value"
      - dbt_expectations.expect_table_row_count_to_be_between:
          arguments:
            min_value: 100000
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_item_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_seller')
                field: seller_id
      - name: order_date
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: order_date
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: "'2016-01-01'"
                max_value: "'2019-01-01'"
      - name: order_status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'approved', 'created']
      - name: price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                strictly: true
      - name: freight_value
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
      - name: total_amount
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                strictly: true
      - name: review_score
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 5
                row_condition: "review_score is not null"
