olist:
  outputs:
    dev:
      dataset: gold
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dataai-project-0
      threads: 4
      type: bigquery
  target: dev
